# Generated by Django 6.0.3 on 2026-06-14 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0002_admissionapplication_applied_under_quota_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('batch_year', models.IntegerField()),
                ('admission_date', models.DateField()),
                ('current_semester', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On Leave'), ('suspended', 'Suspended'), ('graduated', 'Graduated'), ('dropped', 'Dropped'), ('expelled', 'Expelled')], default='active', max_length=20)),
                ('cgpa', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('total_credit_hours_completed', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to='admissions.applicant')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='students', to='academics.degreeprogram')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students_student',
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('medical_conditions', models.TextField(blank=True)),
                ('disabilities', models.TextField(blank=True)),
                ('previous_university', models.CharField(blank=True, max_length=200)),
                ('previous_cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_cnic', models.CharField(blank=True, max_length=15)),
                ('guardian_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_occupation', models.CharField(blank=True, max_length=100)),
                ('residential_address', models.TextField(blank=True)),
                ('permanent_address', models.TextField(blank=True)),
                ('permanent_address_same_as_residential', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='students.student')),
            ],
            options={
                'db_table': 'students_profile',
            },
        ),
    ]
