# Generated by Django 6.0.3 on 2026-04-11 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(blank=True, max_length=100)),
                ('cnic', models.CharField(blank=True, max_length=13)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(default='Pakistani', max_length=50)),
                ('marital_status', models.CharField(blank=True, max_length=20)),
                ('perm_country', models.CharField(blank=True, max_length=50)),
                ('perm_state', models.CharField(blank=True, max_length=50)),
                ('perm_city', models.CharField(blank=True, max_length=50)),
                ('perm_address', models.TextField(blank=True)),
                ('emergency_name', models.CharField(blank=True, max_length=100)),
                ('emergency_relation', models.CharField(blank=True, max_length=50)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('guardian_name', models.CharField(blank=True, max_length=100)),
                ('guardian_cnic', models.CharField(blank=True, max_length=13)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('profile_image', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='applicant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_applicant',
            },
        ),
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(max_length=50, unique=True)),
                ('admission_type', models.CharField(choices=[('Regular', 'Regular'), ('Lateral', 'Lateral'), ('Migration', 'Migration')], default='Regular', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admissions_application',
            },
        ),
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authority', models.CharField(max_length=200)),
                ('qualification_level', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=200)),
                ('institute', models.CharField(max_length=200)),
                ('roll_number', models.CharField(blank=True, max_length=20)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField()),
                ('grading_system', models.CharField(choices=[('marks', 'Marks'), ('cgpa', 'CGPA')], default='marks', max_length=10)),
                ('obtained', models.DecimalField(decimal_places=2, max_digits=7)),
                ('total', models.DecimalField(decimal_places=2, max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='admissions.applicant')),
            ],
            options={
                'db_table': 'admissions_academic_record',
            },
        ),
        migrations.CreateModel(
            name='ProgramPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=200)),
                ('preference_order', models.CharField(max_length=30)),
                ('department', models.CharField(default='Faculty of Computing & IT', max_length=200)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='admissions.admissionapplication')),
            ],
            options={
                'db_table': 'admissions_program_preference',
            },
        ),
    ]
