# Generated by Django 6.0.3 on 2026-06-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='applied_under_quota',
            field=models.CharField(choices=[('open_merit', 'Open Merit'), ('minority', 'Minority'), ('disabled', 'Disabled'), ('sports', 'Sports')], default='open_merit', max_length=30),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_documents_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_eligible',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='is_fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='program',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='applications', to='academics.degreeprogram'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='session_type',
            field=models.CharField(blank=True, choices=[('spring', 'Spring'), ('fall', 'Fall'), ('summer', 'Summer')], max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='session_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('under_review', 'Under Review'), ('documents_pending', 'Documents Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist'), ('registered', 'Registered')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='cnic',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.CreateModel(
            name='AdmissionDecision',
            fields=[
                ('decision_id', models.AutoField(primary_key=True, serialize=False)),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlist', 'Waitlist')], max_length=20)),
                ('decision_date', models.DateField(auto_now_add=True)),
                ('merit_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('merit_position', models.IntegerField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('registration_deadline', models.DateField(blank=True, null=True)),
                ('offered_section', models.CharField(blank=True, max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='decision', to='admissions.admissionapplication')),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_decisions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_decision',
            },
        ),
        migrations.CreateModel(
            name='AdmissionLog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('action_type', models.CharField(choices=[('created', 'Created'), ('submitted', 'Submitted'), ('reviewed', 'Reviewed'), ('documents_verified', 'Documents Verified'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], max_length=50)),
                ('previous_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(blank=True, max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='admissions.admissionapplication')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='admission_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admissions_log',
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('matric_certificate', 'Matric Certificate'), ('fsc_certificate', 'FSc Certificate'), ('cnic_front', 'CNIC Front'), ('cnic_back', 'CNIC Back'), ('photo', 'Passport Photo'), ('domicile', 'Domicile'), ('father_cnic', 'Father CNIC'), ('other', 'Other')], max_length=50)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('verification_remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='admissions.applicant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'applicant_document',
                'unique_together': {('applicant', 'document_type')},
            },
        ),
    ]
