# Generated by Django 6.0.3 on 2026-06-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.AutoField(primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100, unique=True)),
                ('department_code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('semester_id', models.AutoField(primary_key=True, serialize=False)),
                ('semester_name', models.CharField(max_length=50, unique=True)),
                ('academic_year', models.IntegerField()),
                ('semester_type', models.CharField(choices=[('fall', 'Fall'), ('spring', 'Spring'), ('summer', 'Summer')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('registration_start_date', models.DateField()),
                ('registration_end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'semester',
            },
        ),
        migrations.CreateModel(
            name='DegreeProgram',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('program_name', models.CharField(max_length=200)),
                ('program_code', models.CharField(max_length=20, unique=True)),
                ('degree_level', models.CharField(choices=[('BS', 'BS'), ('MS', 'MS'), ('PhD', 'PhD'), ('ADP', 'ADP')], max_length=10)),
                ('duration_years', models.IntegerField()),
                ('total_semesters', models.IntegerField()),
                ('total_credit_hours', models.IntegerField()),
                ('program_type', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('self_support', 'Self Support'), ('distance_learning', 'Distance Learning')], default='morning', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('accepting_admissions', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('fee_per_semester', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='programs', to='academics.department')),
            ],
            options={
                'db_table': 'degree_program',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', models.CharField(max_length=20, unique=True)),
                ('course_name', models.CharField(max_length=200)),
                ('credit_hours', models.IntegerField()),
                ('theory_credit_hours', models.IntegerField(default=0)),
                ('lab_credit_hours', models.IntegerField(default=0)),
                ('course_type', models.CharField(choices=[('core', 'Core'), ('elective', 'Elective'), ('university_requirement', 'University Requirement')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='courses', to='academics.department')),
            ],
            options={
                'db_table': 'course',
            },
        ),
    ]
